### ISSUE TITLE
test_kine errors

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/talos_integration_tests#3]
Hi,

Using #1 & #2, I get this error:

```
Failure happened during one_iteration(): when calling getControl 
/local/robotpkg/var/tmp/robotpkg/wip/py-roscontrol-sot/work/roscontrol_sot-0.5.0/src/roscontrol-sot-controller.cpp 960
In SignalPtr: SIN ptr not set. (in signal <Device(PYRENE)::input(double)::control>)
[ERROR] [1589193865.503502024, 8.928000000]: Failure happened during one_iteration evaluation: std::exception
Use gdb to investiguate the problem
/local/robotpkg/var/tmp/robotpkg/wip/py-roscontrol-sot/work/roscontrol_sot-0.5.0/src/roscontrol-sot-controller.cpp:1075
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
No handlers could be found for logger "rosout"
Aborted (core dumped)
```

Here are multiple things:
1. What is this `/local/robotpkg/` ? I installed everything from the binaries…
2. This `In SignalPtr: SIN ptr not set. (in signal <Device(PYRENE)::input(double)::control>)` is self-explanatory
3. `No handlers could be found for logger "rosout"` I'm probably missing something in my ROS setup. Any clue ?

**Comment by nim65s** [comment]
According to http://wiki.ros.org/rospy_tutorials/Tutorials/Logging:

> NOTE: Your messages will not appear on the /rosout Topic until your Node is fully initialized, so you may not see the initial messages. When you see a message in stdout No handlers could be found for logger "rosout", it's likely either the initialization hasn't finished, or you forgot to call rospy.init_node.

**Comment by nim65s** [comment]
for (1), if @olivier-stasse doesn't know what is this path, I'll suspect that this is the path where this package has been built on robotpkg buildfarm. In this case, I guess that this mean it wasn't build in Release mode.

**Comment by nim65s** [comment]
@olivier-stasse @jmirabel : Do you have any idea for this `In SignalPtr: SIN ptr not set. (in signal <Device(PYRENE)::input(double)::control>)` ? This is blocking for @AlexKuen

With ROS, I have no idea what is run from where. Maybe this plug is failing ?

https://github.com/stack-of-tasks/sot-talos/blob/0d5d490b0197e01c07eaea748f0126e10f6348e7/tests/appli.py#L34

**Comment by jmirabel** [comment]
I suspect your file is sent, but the command are not executed because one of the command before failed, for some reason. In this case, the execution does not stop with a clear message but continues.

In the ros log of the node running SoT (or the one named *talos_integration_tests*), you should have more information.

**Comment by olivier-stasse** [comment]
Sorry guys I did not see the message before. The point of @jmirabel is correct.
In this case, to debug you should do :
```
rosrun talos_integration_tests start_talos_gazebo_kine.py &> /tmp/output.dat
```
and look at the fist errors in the file /tmp/output.dat
You can also look into the log using
```
roscd log
```
and check the output of 
```
 test_kine_py-9-stdout.log
```

**Comment by nim65s** [comment]
Thanks. I found an import issue. I fixed it, and now I don't see any error anymore, but I still have this `In SignalPtr: SIN ptr not set. (in signal <Device(PYRENE)::input(double)::control>)`.

Here are my [output.dat](https://framabin.org/p/?f2a8b12f558be966#ibuKbwyBtoNZAqGofSbEWbPK+kqdB4vRkDEz0IhJ/X8=) and my [test_kine_py-9-stdout.log](https://framabin.org/p/?4149779b6336c68b#kWBgiyUdq7bow3nbHLHEQSpS4P2/YR0ZUpod5jslfZw=)

**Comment by jmirabel** [comment]
Hard to debug with so few info. Wait for @olivier-stasse to see if he has any hints. Otherwise, can this be reproduced in a docker ?

**Comment by nim65s** [comment]
I am only using a docker here, provided in #1 
It is using robotpkg-py27-talos-dev & nvidia drivers for docker. If you don't have an nvidia card, I can provide another version.

**Comment by jmirabel** [comment]
I don't need gazeo gui for this so no worries.

**Comment by nim65s** [comment]
Fixed by https://github.com/stack-of-tasks/sot-talos/pull/23

**Comment by olivier-stasse** [comment]
Thanks @nim65s the Dockerfile is a great addition
